site:
  title: Clusterless Docs
  url: https://docs.clusterless.io
  start_page: guide::index.adoc
  keys:
    plausible-analytics: true

content:
  sources:
    - url: https://github.com/ClusterlessHQ/docs.clusterless.io.git
      branches: wip-1.0
      start_path: docs
      edit_url: '{web_url}/edit/wip-1.0/{path}'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
