site:
  title: Clusterless Docs
  start_page: guide::index.adoc
  keys:
    plausible-analytics: false

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
    - url: ../clusterless
      branches: HEAD
      start_path: .
    - url: ../tessellate
      branches: HEAD
      start_path: tessellate-main/src/main/antora

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

antora:
  extensions:
  - '@antora/collector-extension'
