= Install and Run Quickstart
:keywords:
:navtitle: Install and Run Quickstart

Clusterless relies on the AWS CDK binary.

Both Clusterless and the CDK must be independently bootstrapped. Bootstrapping initializes a cloud provider account and
region for use with the CDK and Clusterless.

The AWS CDK binary is a Node.js app, so Node.js must be installed.

All three can be installed on macOS via Homebrew.

== Install via Homebrew

https://brew.sh[Homebrew] is the easiest way to install the AWS CDK and Clusterless on macOS:

[,console]
----
$ brew install aws-cdk
$ cdk --version
----

Be sure to <<post-cdk-install,bootstrap the AWS CDK>>.

[,console]
----
$ brew tap clusterlesshq/tap
$ brew install clusterless
$ cls --version
----

Be sure to <<bootstrapping,bootstrap a cloud placement>>.

== Other Install

=== AWS CDK

If you don't have Node.js installed, you can install it via: https://nodejs.org/en/download.

See the guide on the AWS site to install the latest version:

- https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html

[,console]
----
$ npm install -g aws-cdk
----

=== Installing Clusterless

The Clusterless CLI app `cls` is downloadable from GitHub releases:

- https://github.com/ClusterlessHQ/clusterless/releases

Download and unzip. Add the `bin` folder to your `PATH`.

The `bin` folder will have:

- `cls` - the root CLI interface
- `cls-aws` - the AWS interface only used as an escape hatch and testing

[#post-cdk-install,reftext=Post CDK Install]
== Post CDK Install

After installation, make sure to bootstrap your account and region:

- https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-howto

[,console]
----
$ cdk bootstrap aws://ACCOUNT-NUMBER-1/REGION-1 aws://ACCOUNT-NUMBER-2/REGION-2 ...
----

[#bootstrapping,reftext=Bootstrapping]
== Bootstrapping a Cloud Placement

Clusterless must bootstrap a cloud provider account within a given region, called a placement.

This is not the same as bootstrapping the AWS CDK (as outlined above).

To perform a bootstrap, call:

[,console]
----
$ cls bootstrap
----

Or with a specific AWS profile:

[,console]
----
$ cls bootstrap --profile [profile name]
----

This will start an interactive session that asks for the necessary xref:concepts:placement.adoc[placement] data:

- provider
- account id
- region
- optional stage (the prefix to use for all resources)

Alternatively, you can call:

[,console]
----
$ cls bootstrap --providers aws --account [account] --region [region] --stage  [stage]
----

Where stage may be left blank.

== Using Clusterless

Next visit xref:guide:howtos:index.adoc[] to see guides on using clusterless.

For working code, check out these repositories:

- https://github.com/ClusterlessHQ/clusterless-aws-examples[clusterless-aws-examples]
- https://github.com/ClusterlessHQ/aws-s3-log-pipeline[aws-s3-log-pipeline]
