= Viewing Status

Clusterless maintains a rich set of metadata.

== Placements

The `cls placements` command will show all placements to the current profile.

[source,console]
----
provider  stage  account       region
========================================
aws       dev    123456789012  us-east-2
----

provider:: The cloud provider name.
stage:: The stage name.
account:: The account number.
region:: The region.

== Projects

The `cls projects` command will show all projects deployed into which placements.

[source,console]
----
placement  placement  placement     placement  project  project
provider   stage      account       region     name     version
===================================================================
aws        dev        123456789012  us-east-2  AwsLogs  20230817-00
----

projectName:: The project name.
projectVersion:: The project version.

== Arcs

The `cls arcs` command will show all arcs deployed into which projects.

[source,console]
----
placement  placement  placement     placement  project  project
provider   stage      account       region     name     version      name
===================================================================================
aws        dev        123456789012  us-east-2  AwsLogs  20230817-00  addPartitions
aws        dev        123456789012  us-east-2  AwsLogs  20230817-00  convertParquet
----

- name - The arc name

The `cls arcs status` command will show a summary of the status of all the arcs.

NOTE: The `cls arcs status --list` command will show all instances of all arcs.

[source,console]
----
placement  placement  placement     placement  project  project                      temporal                   earliest         earliest                   latest           latest                                       total         range
provider   stage      account       region     name     version      name            unit      earliest         found            gap       latest           found            gap     running  partial  missing  complete  found  range  gap
=============================================================================================================================================================================================================================================
aws        dev        123456789012  us-east-2  AwsLogs  20230817-00  addPartitions   TWELFTHS  20231108PT5M195  20231108PT5M195  0         20231109PT5M050  20231109PT5M049  1       0        0        0        143       143    144    1
aws        dev        123456789012  us-east-2  AwsLogs  20230817-00  convertParquet  TWELFTHS  20231108PT5M195  20231108PT5M195  0         20231109PT5M050  20231109PT5M050  0       1        0        0        143       144    144    0

----

temporalUnit:: The temporal unit that defines the duration of at lot
earliest:: The earliest requested arc lot id in requested range
earliestFound:: The first arc instance that was found
earliestGap:: The number of intervals between the earliest and the earliestFound arcs
latest:: The latest requested arc lot id in requested range
latestFound:: The last arc instance that was found
latestGap:: The number of intervals between the latest and the latestFound arcs
running:: The number of arc instances that are currently running, creating data
partial:: The number of arc instances that ended with partially complete data
missing:: The number of arc instances that have missing data, may have missing source data
complete:: The number of arc instances that ended successfully, with complete data
totalFound:: The total number of arc instances that have been found
range:: The total number of arc instances that should have been found in the requested range
rangeGap:: The number of arc instances that are missing from the requested range

== Datasets

The `cls datasets` command will show all datasets deployed.

[source,console]
----
placement  placement  placement     placement  dataset              dataset
provider   stage      account       region     name                 version
============================================================================
aws        dev        123456789012  us-east-2  access-logs-parquet  20230817
aws        dev        123456789012  us-east-2  partitions           20230817
aws        dev        123456789012  us-east-2  s3-access-logs       20230817
----

dataset.name:: The dataset name.
dataset.version:: The dataset version.

The `cls datasets status` command will show a summary of the status of all the datasets.

NOTE: The `cls datasets status --list` command will show all instances of all manifests.

[source,console]
----
placement  placement  placement     placement  dataset              dataset   temporal                   earliest         earliest                   latest           latest                                     total         range
provider   stage      account       region     name                 version   unit      earliest         found            gap       latest           found            gap     removed  partial  empty  complete  found  range  gap
====================================================================================================================================================================================================================================
aws        dev        123456789012  us-east-2  access-logs-parquet  20230817  TWELFTHS  20231108PT5M195  20231108PT5M195  0         20231109PT5M050  20231109PT5M050  0       0        0        24     120       144    144    0
aws        dev        123456789012  us-east-2  partitions           20230817  TWELFTHS  20231108PT5M195  20231108PT5M195  0         20231109PT5M050  20231109PT5M049  1       0        0        24     119       143    144    1
aws        dev        123456789012  us-east-2  s3-access-logs       20230817  TWELFTHS  20231108PT5M195  20231108PT5M195  0         20231109PT5M050  20231109PT5M050  0       0        0        24     120       144    144    0
----

temporalUnit:: The temporal unit that defines the duration of at lot.
earliest:: The earliest requested manifest lot id in requested range.
earliestFound:: The first manifest that was found.
earliestGap:: The number of intervals between the earliest and the earliestFound manifests.
latest:: The latest requested manifest lot id in requested range.
latestFound:: The last manifest that was found.
latestGap:: The number of intervals between the latest and the latestFound manifests.
removed:: The number of manifests, and their data, that were removed.
partial:: The number of manifest that contain partially complete data.
empty:: The number of manifests that have no data, may have no source data.
complete:: The number of manifests that contain complete data.
totalFound:: The total number of manifests that have been found.
range:: The total number of manifests that should have been found in the requested range.
rangeGap:: The number of manifests that are missing from the requested range.
